name: GitHub Page

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

permissions:
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-20.04

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node.JS
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: npm

    - name: Install Dependencies
      run: npm ci

    - name: Generate
      run: |
        npm run lint
        npm run build
        npm run minify
        cp .gitignore public/

    - name: Store pages
      uses: actions/upload-pages-artifact@v2
      with:
        path: public

    - name: Deploy
      if: github.event_name == 'push'
      id: deployment
      uses: actions/deploy-pages@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
